---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: prod
spec:
  encryptedData:
    foo: AgARzUs7QZS42/Ovyp0Qs98Ku4H0qdrnTfVbKXxaE6daegpE3yMkzvk/92uoCXfkXfA9IosEvKmS+9lNAq02kID+4vCwz6/P6NE93/15eGtE8fCrI92b7VKaIPjWNxWbTMh6nSXvSpCq190N8ITRFiTplu3XN27PyaTQSnK53rJwGqVXFTvIdJ57t24FgATtzCt4g08Q7gh172RY8hrBqRaIvyRlwRGzZj/FJHPca/eIiRPvL9fSDKKZUPNhzcvMFeMN6IH1ESoxFHr5WMIH5/ieM5+4NgphyP8LHq2Xs9/bdw2UpTAWcfdNubKSzQVAJrgyNTH6jK1v2kB+OnaMC7AUmEeHSvtycm7yzJKIlrkSpP3DSCnJAiVn3eIib3Q/duWX/YJ4zhBr74i2Ov53xW8zuIG7qCEUtFPPdq0j47cJX4Loy2Nrlv1r2SnoAXeAttBNo1qDCapK1Htu/GYT6M1OiGBQO7Ger5re6U53VuEqBaMJmKETFZGz5xosgYx3bAjpcnGOp7B2loQO7+uh9uei0q4SOl98tYq+kpz1xJ3af+U6MyilEmuTx06kXtCMp7HIHL5o74hP0pHuPpW0XOA4do5UeLrWTMgtBalEQ5w+nbpRDsNAmos4WygwxAJwxhlDE0NbGmdVfofpzS6JF7XvJomA+KuRBeoE8+5VpgdH75Stn6fytHLPoOuHvZSAwcvuVLY=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: prod
